language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.7
notifications:
    email: false
addons:
    apt:
        packages:
            - python3-sphinx
            - libevent-dev
            - libhdf5-dev
cache:
    - directories:
          - tests/simulate-chime/kotekan
          - tests/simulate-chime/highfive
env:
    global:
        - MAKEFLAGS="-j 2"
        - TEST_DIR="$TRAVIS_BUILD_DIR/tests/simulate-chime/"

services:
    - docker
    - redis-server

before_install:
    - pip install black
    - pip install pydocstyle

install:
    - pip install -r requirements.txt
    - pip install .

script:
    # Run black on all .py files in all subfolders
    - black -l 99 --check --exclude kotekan .

    # Run pydocstyle on all .py files
    - find . -type d \( -path ./docs -o -path ./tests/simulate-chime \) -prune -o ! -name versioneer.py ! -name _version.py -name \*.py -exec pydocstyle --convention=numpy {} +

    # Build docs
    - cd docs
    - make html
    - cd ..
