language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.7
notifications:
    email: false
addons:
    apt:
        packages:
            - python3-sphinx
            - libevent-dev
            - libhdf5-dev
            - g++
env:
    global:
        - MAKEFLAGS="-j 2"
        - TEST_DIR="$TRAVIS_BUILD_DIR/tests/simulate-chime/"

services:
    - docker
    - redis-server

before_install:
    - pip install black
    - pip install pydocstyle
    - pip install flask  # for unit tests
    - pip install coverage
    - pip install pytest-cov

install:
    - pip install -r requirements.txt
    - pip install .

script:
    # Run black on all .py files in all subfolders
    - black --check --exclude kotekan .

    # Run pydocstyle on all .py files
    - find . -type d \( -path ./docs -o -path ./tests/simulate-chime \) -prune -o ! -name versioneer.py ! -name test_*.py ! -name _version.py -name \*.py -exec pydocstyle --convention=numpy --add-ignore=D105,D202 {} +

    # Build docs
    - cd docs
    - make html
    - cd ..

    - g++ -o tests/hash tests/hash.cpp --std=c++11 -lssl -lcrypto

    # Run unit tests
    - PYTHONPATH=. pytest -xs --cov-report term-missing:skip-covered --cov=coco tests/test_*.py
