[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
name = "coco"
authors = [
  { name = "The CHIME Collaboration", email = "dvw@phas.ubc.ca" }
]
maintainers = [
    { name = "Liam Gray", email = "lgray@phas.ubc.ca" },
    { name = "Adam Lanman", email = "alanman@mit.edu" },
    { name = "Don Wiebe", email = "dvw@phas.ubc.ca" }
]
description = "The CHIME Config Controller"
requires-python = ">=3.10"
dynamic = ["readme", "version"]
license = "GPL-3.0-or-later"
license-files = [ "LICENSE" ]
dependencies = [
  "comet @ git+https://github.com/chime-experiment/comet.git",
  "aiohttp",
  "async_timeout",
  "click>=8.2",
  "deepdiff",
  "jinja2",
  "mmh3",
  "msgpack",
  "prometheus_client<0.8",
  "pyyaml",
  "redis>=4.2.0",
  "sanic>=20.6.0"
]

[project.optional-dependencies]
test = [
  "fakeredis[lua]",
  "pyfakefs >= 5.4",
  "pytest >= 7.0"
]

[project.scripts]
cocod = "coco.core:cocod"
coco = "coco.client:entry"

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages]
find = {}

[tool.setuptools-git-versioning]
enabled = true

[tool.ruff]
lint.select = ["E", "F", "I", "UP", "NPY", "RUF", "BLE", "C4", "RET"]
