name: coco-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pip dependencies
        run: |
          pip install black pydocstyle flake8 pylint pylint-ignore
          pip install -r requirements.txt

      - name: Check code with black
        run: black --check --exclude kotekan .

      - name: Run black on scripts
        run: black --check scripts/cocod scripts/coco

      - name: Run pydocstyle on all .py files
        run: find . -type d \( -path ./docs -o -path ./tests/simulate-chime \) -prune -o ! -name versioneer.py ! -name test_*.py ! -name _version.py -name \*.py -exec pydocstyle --convention=numpy --add-ignore=D105,D202 {} +

      - name: Run flake8
        run: flake8 --show-source --ignore=E501,E741,E203,W503,E266,E402 coco

      - name: Run pylint
        run: pylint-ignore -d line-too-long,invalid-name,logging-fstring-interpolation,too-many-arguments,too-many-instance-attributes --ignore=_version.py coco

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ 3.6, 3.7 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install apt dependencies
        run: |
          sudo apt-get install -y python3-sphinx libevent-dev libhdf5-dev g++
      - name: Install pip dependencies
        run: |
          pip install flask coverage pytest-cov sphinx_rtd_theme
          pip install -r requirements.txt
          pip install .

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 5

      - name: Build docs
        run: cd docs && make html && cd ..

      - name: Build test utils
        run: MAKEFLAGS="-j 2" g++ -o tests/hash tests/hash.cpp --std=c++11 -lssl -lcrypto

      - name: Unit tests
        run: PYTHONPATH=. TEST_DIR="GITHUB_WORKSPACE/tests/simulate-chime/" pytest -xs --cov-report term-missing:skip-covered --cov=coco tests/test_*.py
